CREATE TABLE EDDA_FB_Post (
   Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY, 
   Autore VARCHAR(50) NOT NULL,
   Testo VARCHAR(255) NOT NULL,
   [Like] INT NOT NULL);

ALTER TABLE [dbo].[EDDA_FB_Post] ADD  CONSTRAINT [DF_EDDA_FB_Post_Like]  DEFAULT ((0)) FOR [Like];